name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}          
          
      - name: Run type check
        run: pnpm run typecheck

      # - name: Run ESLint
      #   run: pnpm run lint

      - name: Run tests
        run: pnpm run test
